project:
  name: 'spark-connector'
  tag: 'spart-connector'
  url: 'https://docs.mongodb.org/'
  title: 'MongoDB Spark Connector Manual'
  branched: fale
  siteroot: false
version:
  release: '1.0'
  branch: 'master'
system:
  make:
    generated:
      - 'meta'
      - 'integration'
      - 'sphinx'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
  files:
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - 'push.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: http://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...