# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys
code: 301
from: '/'
to: '/v1.1'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/configuration'
to: '/v1.1/configuration'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/faq'
to: '/v1.1/faq'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/getting-started'
to: '/v1.1/getting-started'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/java-api'
to: '/v1.1/java-api'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/python-api'
to: '/v1.1/python-api'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/spark-sql'
to: '/v1.1/spark-sql'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/sparkR'
to: '/v1.1/sparkR'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
...
