# Each YAML document has the following schema:
#
# from: "the path to the redirected URL"
# to: "the path to the new location for the resource"
# type: "currently this script only supports 'redirect', and
#        ignores all documents with another type."
# code: "the HTTP redirect code. Raises exception if not 301, 302, 303."
# outputs: "a list of branches/paths as follows:"
#
# - 'all': generates redirects for all published branches, but *not* 'manual'. But giza will take care of manual as part of integration.yaml logic in redirects.py
#
# - '<branch>': generates redirects for a specific branch.
#
# - 'before-<branch>': generates redirects for all branches that
#   reflect releases previous to the specified branch. (Inclusive.)
#
# - 'after-<branch>': generates redirects for all branches that
#   reflect releases after the specified branch. (Non-inclusive.)
#
# All paths are relative to the ``source/`` directory.
#
########################################################################
### Giza requires this file, even if no redirects
### More as a safety -- in case, we remove redirects during deploys
code: 301
from: '/'
to: '/v2.0'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/configuration'
to: '/v2.0/configuration'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/faq'
to: '/v2.0/faq'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/getting-started'
to: '/v2.0'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/java-api'
to: '/v2.0/java-api'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/python-api'
to: '/v2.0/python-api'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/spark-sql'
to: '/v2.0/spark-sql'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/sparkR'
to: '/v2.0/r-api'
outputs:
  - {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/python/write-to-mongodb'
to: '/python-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/python/read-from-mongodb'
to: '/python-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/python/aggregation'
to: '/python-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/python/filters-and-sql'
to: '/python-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/scala/write-to-mongodb'
to: '/getting-started'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/scala/read-from-mongodb'
to: '/getting-started'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/scala/aggregation'
to: '/getting-started'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/scala/datasets-and-sql'
to: '/spark-sql'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/java/write-to-mongodb'
to: '/java-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/java/read-from-mongodb'
to: '/java-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/java/aggregation'
to: '/java-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/java/datasets-and-sql'
to: '/java-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/r/write-to-mongodb'
to: '/r-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/r/read-from-mongodb'
to: '/r-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/r/aggregation'
to: '/r-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
---
code: 301
from: '/r/filters-and-sql'
to: '/r-api'
outputs:
  - 'before-v1.1': {'/spark-connector': 'https://docs.mongodb.com/spark-connector'}
type: redirect
...
